spring:
  application:
    name: system-monitoring-management-containers

server:
  port: 8082
  servlet:
    context-path: /monitoring-managment-containers

mongodb:
  host: 0.0.0.0
  port: 27017
  database-name: test
  username: username
  password: password

endpoints:
  docker-engine-api:
    base-url: http://localhost:2375/

